trying consolodating

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,9 +12,7 @@ jobs:
         outputs:
             new_version: ${{ steps.set_version.outputs.new_version }}
         steps:
-            - name: Checkout code
-              uses: actions/checkout@v3
-
+            - uses: actions/checkout@v3
             - name: Check for version file and increment version
               id: set_version
               run: |
@@ -23,41 +21,24 @@ jobs:
                     echo "1.0.0" > "$VERSION_FILE"
                     echo "Created new version file with version 1.0.0"
                   fi
-
                   current_version=$(cat "$VERSION_FILE")
                   echo "Current version: $current_version"
-
-                  # Split the version into parts
                   IFS='.' read -ra VERSION_PARTS <<< "$current_version"
                   MAJOR=${VERSION_PARTS[0]}
                   MINOR=${VERSION_PARTS[1]}
-                  PATCH=${VERSION_PARTS[2]}
-
-                  # Increment patch version
-                  PATCH=$((PATCH + 1))
-
+                  PATCH=$((${VERSION_PARTS[2]} + 1))
                   new_version="${MAJOR}.${MINOR}.${PATCH}"
                   echo "New version: $new_version"
-
-                  # Save new version to file
                   echo "$new_version" > "$VERSION_FILE"
-
-                  # Set output for use in other jobs
                   echo "new_version=$new_version" >> $GITHUB_OUTPUT
-
             - name: Commit and push new version
               run: |
                   git config user.name github-actions
                   git config user.email github-actions@github.com
                   git add version.txt
                   git commit -m "Bump version to ${{ steps.set_version.outputs.new_version }}"
-
-                  # Authenticate using GITHUB_TOKEN
                   git remote set-url origin "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
                   git push origin
-              env:
-                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
             - name: Create and push tag
               run: |
                   git tag -a v${{ steps.set_version.outputs.new_version }} -m "Version ${{ steps.set_version.outputs.new_version }}"
@@ -67,18 +48,11 @@ jobs:
         needs: generate-version
         runs-on: ubuntu-latest
         steps:
-            - name: Checkout code
-              uses: actions/checkout@v3
-
+            - uses: actions/checkout@v3
             - name: Install dependencies
               run: yarn install
-
             - name: Build app
               run: yarn build
-
-            - name: List contents of project directory
-              run: ls -al .next
-
             - name: Upload build artifact
               uses: actions/upload-artifact@v4
               with:
@@ -87,20 +61,18 @@ jobs:
                   include-hidden-files: true
 
     test:
-        runs-on: ubuntu-latest
         needs: setup-and-build
+        runs-on: ubuntu-latest
         steps:
-            - name: Checkout code
-              uses: actions/checkout@v3
-
+            - uses: actions/checkout@v3
             - name: Download build artifact
               uses: actions/download-artifact@v4
               with:
                   name: build-artifacts
                   path: .next
-
             - name: Install dependencies
               run: yarn install
+<<<<<<< HEAD
 
             - name: Run app
               run: yarn start &
@@ -113,91 +85,74 @@ jobs:
 
             - name: Stop app
               run: pkill node
+=======
+            - name: Run and test app
+              run: |
+                  yarn start &
+                  sleep 10
+                  curl http://localhost:3000 --fail --connect-timeout 10 --max-time 30
+                  pkill node || (echo "Failed to stop Node process." && exit 1)
+>>>>>>> acc5c92 (trying consolodating)
 
     docker-build:
-        runs-on: ubuntu-latest
         needs: setup-and-build
+        runs-on: ubuntu-latest
         steps:
-            - name: Checkout code
-              uses: actions/checkout@v3
-
+            - uses: actions/checkout@v3
             - name: Download build artifact
               uses: actions/download-artifact@v4
               with:
                   name: build-artifacts
-                  path: .next # Download the .next directory
-
+                  path: .next
             - name: Read version file
               id: version
               uses: juliangruber/read-file-action@v1
               with:
                   path: ./version.txt
-
-            - name: Build Docker image
-              run: docker build -t crm-app:$(echo "${{ steps.version.outputs.content }}" | tr -d '\n') .
-
-            - name: Start E2E Environment
-              run: docker compose up -d
-
-            # # - name: Run E2E tests #TODO create e2e tests
-            # #   run: yarn test:e2e
-
-            - name: curl test
+            - name: Build and test Docker image
               run: |
-                  sleep 5 # Wait for E2E env if needed
+                  docker build -t crm-app:$(echo "${{ steps.version.outputs.content }}" | tr -d '\n') .
+                  docker compose up -d
+                  sleep 5
                   curl http://localhost:80 --fail --connect-timeout 10 --max-time 30
-
-            - name: Stop E2E Environment
-              run: docker compose down
-
-            - name: Save Docker image
-              run: docker save crm-app:$(cat version.txt) > image.tar
-
-            - name: Upload Docker image artifact
+                  docker compose down
+            - name: Save and upload Docker image
+              run: |
+                  docker save crm-app:$(cat version.txt) > image.tar
+            - name: Upload Docker image
               uses: actions/upload-artifact@v4
               with:
                   name: docker-image
                   path: image.tar
 
     docker-push:
-        runs-on: ubuntu-latest
         needs: docker-build
+        runs-on: ubuntu-latest
         steps:
-            - name: configure AWS credentials
+            - uses: actions/checkout@v3
+            - name: Configure AWS credentials
               uses: aws-actions/configure-aws-credentials@v3
               with:
                   aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                   aws-region: ${{ secrets.AWS_REGION }}
-
-            - name: Download Docker image artifact
-              uses: actions/download-artifact@v4
-              with:
-                  name: docker-image
-
-            - name: Load Docker image
-              run: docker load < image.tar
-
-            - name: checkout code
-              uses: actions/checkout@v3
-
-            - name: read version
+            - name: Download and load Docker image
+              run: |
+                  actions/download-artifact@v4
+                  with:
+                    name: docker-image
+                  docker load < image.tar
+            - name: Read version
               id: version
               uses: juliangruber/read-file-action@v1
               with:
                   path: ./version.txt
-
-            - name: Login to Amazon ECR
-              run: aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com
-
-            - name: Tag Docker image
+            - name: Push to ECR
               run: |
+                  aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com
                   VERSION="${{ steps.version.outputs.content }}"
                   VERSION="${VERSION//$'\n'}"
                   docker tag "crm-app:${VERSION}" "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/crm-app:${VERSION}"
-
-            - name: Push Docker image to ECR
-              run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/crm-app:${{ steps.version.outputs.content }}
-
+                  docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/crm-app:${VERSION}
             - name: All done
-              run: echo "All done!!!!!!!!!!!!!"
+              run: echo "All done!"
